# Generated by Django 5.1.1 on 2024-10-05 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(default='', max_length=50, verbose_name='Category (English)')),
                ('name_ru', models.CharField(default='', max_length=50, verbose_name='Категория (Русский)')),
                ('name_uz', models.CharField(default='', max_length=50, verbose_name="Kategoriya (O'zbek)")),
                ('is_linked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(default='', max_length=50, verbose_name='Country (English)')),
                ('name_ru', models.CharField(default='', max_length=50, verbose_name='Страна (Русский)')),
                ('name_uz', models.CharField(default='', max_length=50, verbose_name="Davlat (O'zbek)")),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='product-image/default.jpg', upload_to='product-image')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=900, null=True, verbose_name='Описание')),
                ('telephone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('telephone_view_count', models.PositiveBigIntegerField(default=0, verbose_name='Количество просмотров номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграмм номер')),
                ('view_count', models.PositiveBigIntegerField(default=0, verbose_name='Количество просмотров')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=50)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('is_price_negotiable', models.BooleanField(default=False, verbose_name='Договорная цена')),
                ('is_top_film', models.BooleanField(default=False)),
                ('top_duration', models.PositiveIntegerField(default=0, verbose_name='Продолжительность в топе (в днях)')),
                ('create_date_changed', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(default='', max_length=100, verbose_name='Subcategory (English)')),
                ('name_ru', models.CharField(default='', max_length=100, verbose_name='Подкатегория (Русский)')),
                ('name_uz', models.CharField(default='', max_length=100, verbose_name="Subkategoriya (O'zbek)")),
                ('is_linked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='', max_length=255, unique=True, verbose_name='Tag Name (English)')),
                ('name_ru', models.CharField(default='', max_length=255, unique=True, verbose_name='Имя тега (Русский)')),
                ('name_uz', models.CharField(default='', max_length=255, unique=True, verbose_name="Tag nomi (O'zbek)")),
                ('is_linked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TagSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(default='', max_length=50, verbose_name='Country (English)')),
                ('name_ru', models.CharField(default='', max_length=50, verbose_name='Страна (Русский)')),
                ('name_uz', models.CharField(default='', max_length=50, verbose_name="Davlat (O'zbek)")),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.country')),
            ],
        ),
    ]
