# Generated by Django 5.1.1 on 2024-10-05 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.categories'),
        ),
        migrations.AddField(
            model_name='products',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.city'),
        ),
        migrations.AddField(
            model_name='products',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.country'),
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.products'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.products'),
        ),
        migrations.AddField(
            model_name='products',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='posts.subcategories'),
        ),
        migrations.AddField(
            model_name='subcategorycategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.categories'),
        ),
        migrations.AddField(
            model_name='subcategorycategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.subcategories'),
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(blank=True, to='posts.tag'),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='posts.categories'),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_tags', to='posts.tag'),
        ),
        migrations.AddField(
            model_name='tagsubcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='posts.subcategories'),
        ),
        migrations.AddField(
            model_name='tagsubcategory',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_tags', to='posts.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product_id')},
        ),
    ]
