# Generated by Django 5.1.1 on 2024-11-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='product-image/default.jpg', null=True, upload_to='product-image'),
        ),
    ]
