# Generated by Django 5.1.1 on 2024-11-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/'),
        ),
    ]
